name: deeplink
description: custom deep link clear intent data
version: 0.0.1
homepage: https://github.com/lufimon/flutter_deeplink

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.quantam.deeplink
        pluginClass: DeeplinkPlugin
      ios:
        pluginClass: DeeplinkPlugin
